<?
require_once('common.lib');

if (checkCmpyId()) {
} else {
    exit;
}

$title = 'QnA수집';

$desc = '삽플링 QnA 가져오기';

$url = 'qna/qna_gather_api.phtml';

$request_string = '<reqst>
   <apiQnaGather>
		login_id	로그인ID	<![CDATA[]]>			Y
		company_id	고객사 아이디				Y	shopPling 발급
		api_auth_key	API 인증코드				Y	shopPling 발급
		start_dt	검색시작일자(QnA수집기준일자)		yyyymmdd		Y	31일 이상 넘길수 없습니다.
		end_dt	검색종료일자(QnA집기준일자)		yyyymmdd		Y
		qna_fields	출력 qna필드명(구분자"," 로 여러개가능)	<![CDATA[]]>			Y	qna필드 기술서 참고하여 필요정보 기술
   </apiQnaGather>
</reqst> 								';

$response_string = '<rspns>
   <apiQnaGatherRst>
		login_id	로그인ID	<![CDATA[]]>			Y
		company_id	고객사 아이디				Y	shopPling 발급
      <qnaListRst>	Y
	Y	qna_var_name	qna정보 필드 변수명	<![CDATA[]]>				qna필드 기술서 변수 참조
      </qnaListRst>	Y
		cnt	전체건수					전체 건수
   </apiQnaGatherRst>
</rspns> 								';

$request_example = '<?xml version="1.0" encoding="UTF-8"?>
<reqst>
   <apiQnaGather>
      <login_id><![CDATA[shoppling]]></login_id>
      <company_id>S001</company_id>
      <api_auth_key>fgsddfgfkdgdkfgk</api_auth_key>
      <start_dt>20150201</start_dt>
      <end_dt>20150207</end_dt>
      <claim_fields><![CDATA[qna_key, mall_key, mall_login_id, mall_ord_id, mall_prod_key, mall_prod_nm, prod_id, qna_tp,]]></claim_fields>
   </apiQnaGather>
</reqst>';

$response_example = '<?xml version="1.0" encoding="UTF-8"?>
<rspns>
   <apiQnaGatherRst>
      <login_id><![CDATA[shoppling]]></login_id>
      <company_id>S001</company_id>
      <qnaListRst>
         <qna_key><![CDATA[15698]]></qna_key>
         <mall_key><![CDATA[SMALL00001]]></mall_key>
         <mall_login_id><![CDATA[fkgkgkgkgk]]></mall_login_id>
         <mall_ord_id><![CDATA[자동]]></mall_ord_id>
         <mall_prod_key><![CDATA[취소]]></mall_prod_key>
         <mall_prod_nm><![CDATA[취소접수]]></mall_prod_nm>
         <prod_id><![CDATA[취소접수]]></prod_id>
         <qna_tp><![CDATA[취소접수]]></qna_tp>
      </qnaListRst>
      <qnaListRst>
         <qna_key><![CDATA[156987]]></qna_key>
         <mall_key><![CDATA[SMALL00001]]></mall_key>
         <mall_login_id><![CDATA[fkgkgkgkgk]]></mall_login_id>
         <mall_ord_id><![CDATA[자동]]></mall_ord_id>
         <mall_prod_key><![CDATA[취소]]></mall_prod_key>
         <mall_prod_nm><![CDATA[취소접수]]></mall_prod_nm>
         <prod_id><![CDATA[취소접수]]></prod_id>
         <qna_tp><![CDATA[취소접수]]></qna_tp>
      </qnaListRst>
      <cnt>2</cnt>
   </apiQnaGatherRst>
</rspns>';

require_once('api_content_layout.phtml');

?>