<?
require_once('common.lib');

if ($request_string) {
    $request = apiStringToArray($request_string);
}

if ($response_string) {
    $response = apiStringToArray($response_string);
}
?>

<h3>
    <?=$title?>
    <span class='ver'>(<?=pageLastUpdateDate()?>)</span>
</h3>

<? if ($desc || $url) { ?>
<table>
    <? if ($desc)   { ?><tr> <th width='100'>기능</th>  <td><xmp><?=$desc?>  (아래 둘중 하나 골라서 사용)</xmp></td></tr><? } ?>
    <? if ($url)    { ?><tr> <th>URL</th>               <td><xmp><?=apiURL($url)?></xmp></td>                       </tr><? } ?>
</table>
<? } ?>

<? if (count($request)) { ?>
<span class='info'>※ 필수값이 아니고 해당사항이 없는경우는 미선언 하시면 됩니다.</span>

<table>
    <? echo apiTableHeadHTML('요청'); foreach($request as $row)  { echo apiTableBodyHTML('request',  $row); } ?>
</table>
<? } ?>

<? if (count($response)) { ?>
<table>
    <? echo apiTableHeadHTML('응답'); foreach($response as $row) { echo apiTableBodyHTML('response', $row); } ?>
</table>
<? } ?>

<? if ($request_example)    { ?><h3>XML 요청 예시</h3><div class='code'><pre><xmp><?=$request_example?></xmp></pre></div><?  } ?>

<? if ($response_example)   { ?><h3>XML 응답 예시</h3><div class='code'><pre><xmp><?=$response_example?></xmp></pre></div><? } ?>

<? if ($result_code)        { ?><h3>결과코드리스트</h3><div class='code'><pre><xmp><?=$result_code?></xmp></pre></div><?     } ?>

<?
$title = $desc = $url = $request_example = $response_example = $result_code = $request_string = $response_string = '';

$request = $response = array();
?>